// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitalBand.Data;

#nullable disable

namespace VitalBand.Migrations
{
    [DbContext(typeof(VitalBandContext))]
    [Migration("20260721225609_AddAtendidaToAlertas")]
    partial class AddAtendidaToAlertas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VitalBand.Models.Alerta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<bool?>("atendida")
                        .HasColumnType("tinyint(1)");

                    b.Property<float?>("fc_media")
                        .HasColumnType("float");

                    b.Property<DateTime?>("fecha_hora")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("hrv_rmssd")
                        .HasColumnType("float");

                    b.Property<float?>("latitud")
                        .HasColumnType("float");

                    b.Property<float?>("longitud")
                        .HasColumnType("float");

                    b.Property<bool?>("mensaje_enviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("paciente_id")
                        .HasColumnType("int");

                    b.Property<float?>("spo2_estabilidad")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("paciente_id");

                    b.ToTable("ALERTAS");
                });

            modelBuilder.Entity("VitalBand.Models.ContactoEmergencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("paciente_id")
                        .HasColumnType("int");

                    b.Property<string>("parentesco")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("prioridad")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.HasIndex("paciente_id");

                    b.ToTable("CONTACTOS_EMERGENCIA");
                });

            modelBuilder.Entity("VitalBand.Models.Medico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cedula_profesional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("usuario_id");

                    b.ToTable("MEDICOS");
                });

            modelBuilder.Entity("VitalBand.Models.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<float?>("altura_inicial")
                        .HasColumnType("float");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("genero")
                        .HasColumnType("longtext");

                    b.Property<string>("historial_medico_breve")
                        .HasColumnType("longtext");

                    b.Property<int?>("medico_asignado_id")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float?>("peso_inicial")
                        .HasColumnType("float");

                    b.Property<string>("tipo_sangre")
                        .HasColumnType("longtext");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("medico_asignado_id");

                    b.HasIndex("usuario_id");

                    b.ToTable("PACIENTES");
                });

            modelBuilder.Entity("VitalBand.Models.PacientePatologia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("paciente_id")
                        .HasColumnType("int");

                    b.Property<int>("patologia_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("paciente_id");

                    b.HasIndex("patologia_id");

                    b.ToTable("PACIENTES_PATOLOGIAS");
                });

            modelBuilder.Entity("VitalBand.Models.PatologiaCatalogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("nombre_enfermedad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("PATOLOGIAS_CATALOGO");
                });

            modelBuilder.Entity("VitalBand.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("sesion_expiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("token_sesion")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("VitalBand.Models.Alerta", b =>
                {
                    b.HasOne("VitalBand.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("VitalBand.Models.ContactoEmergencia", b =>
                {
                    b.HasOne("VitalBand.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("VitalBand.Models.Medico", b =>
                {
                    b.HasOne("VitalBand.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VitalBand.Models.Paciente", b =>
                {
                    b.HasOne("VitalBand.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("medico_asignado_id");

                    b.HasOne("VitalBand.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VitalBand.Models.PacientePatologia", b =>
                {
                    b.HasOne("VitalBand.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("paciente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VitalBand.Models.PatologiaCatalogo", "PatologiaCatalogo")
                        .WithMany()
                        .HasForeignKey("patologia_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("PatologiaCatalogo");
                });
#pragma warning restore 612, 618
        }
    }
}
